# -*- coding: utf-8 -*-
"""Core defenses

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rFThpc1GIPTThyZ8fbLO4yxELFynhOxm

### **CORE Deffenses for the BFLT**
This is the implemnation of core defenses.
"""

import torch
import torch.nn as nn
import numpy as np
from typing import List, Tuple
import copy
import logging

class ByzantineCoreDefense:
    def __init__(self, f: int, device: str = "cuda"):
        self.f = f
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    def flatten_update(self, updates_list: List[List[torch.Tensor]]) -> torch.Tensor:
        flattened = []
        for client_grads in updates_list:
            flat_vector = torch.cat([grad.view(-1) for grad in client_grads])
            flattened.append(flat_vector)
        return torch.stack(flattened).to(self.device)

    def reconstruct_update(self, flat_vector: torch.Tensor, reference_grads: List[torch.Tensor]):
        layer_size = [g.numel() for g in reference_grads]
        chunks = torch.split(flat_vector, layer_size)
        return [c.view_as(ref) for c, ref in zip(chunks, reference_grads)]

    def aggregate(self, updates_list: List[List[torch.Tensor]], method: str = "trimmed_mean"):
        flattened_matrix = self.flatten_update(updates_list)
        n = flattened_matrix.shape[0]

        if method == "trimmed_mean":
            sorted_matrix, _ = torch.sort(flattened_matrix, dim=0)
            aggr_flat = torch.mean(sorted_matrix[self.f : n - self.f], dim=0)

        elif method == "krum":
            distances = torch.cdist(flattened_matrix, flattened_matrix, p=2)
            scores = []
            for i in range(n):
                sorted_dist, _ = torch.sort(distances[i])
                scores.append(sorted_dist[: n - self.f - 1].sum())

            best_idx = torch.argmin(torch.tensor(scores))
            aggr_flat = flattened_matrix[best_idx]

        else:
            aggr_flat = torch.mean(flattened_matrix, dim=0)

        return self.reconstruct_update(aggr_flat, updates_list[0])